/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VaultV1__factory } from "./VaultV1__factory";
export { VaultV2__factory } from "./VaultV2__factory";
